import json
import os
import subprocess
import shutil
from PIL import Image, ImageDraw, ImageFont

# config
TOPOLOGY_FILE = "s2_topology.json"
PREPROCESSOR_EXE = "s2_preprocessor.exe" # Assumed in current dir or path
# If compiled manually, it might be just s2_preprocessor (no exe) or debug/release.
# User said they compiled manually. Let's assume standard compile command output.

# We need the output location. s2_preprocessor output is usually in "output/intermediate/..."
# We will use a temp output dir for these tests.
OUTPUT_DIR = "debug_variants"
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

# Image Params (Match s2_preprocessor config)
FACE_SIZE = 512
PADDING = 64
BANDS = 3

# Helper: Read Topology
def load_topology():
    with open(TOPOLOGY_FILE, 'r') as f:
        return json.load(f)

# Helper: Write Topology
def save_topology(data):
    with open(TOPOLOGY_FILE, 'w') as f:
        json.dump(data, f, indent=4)

# Helper: Run Preprocessor
def run_preprocessor(variant_name):
    # We call it with arguments to execute fast.
    # Args: input_path output_prefix max_zoom
    # We need to point to existing faces.
    # Assuming local faces in "faces/faceX.tif"?
    # Or "output/faceX.tif"?
    # The preprocessor expects "prefix_faceX.tif".
    # Let's assume standard run args.
    # The user runs "python ingest_planet.py ...".
    # We will try to run s2_preprocessor directly if possible.
    # Usage: s2_preprocessor <input_prefix> <output_prefix> <max_zoom>
    
    # We need to look up where the face files are.
    # Current dir usually has "colortest_face0.tif" etc generated by convert_gaia?
    # Let's check typical usage.
    input_prefix = "colortest" # Standard debug prefix
    output_prefix = f"{OUTPUT_DIR}/{variant_name}"
    
    cmd = [f"./{PREPROCESSOR_EXE}", input_prefix, output_prefix, "0"]
    # We only need level 0 strips.
    
    # Check if exe exists
    if not os.path.exists(PREPROCESSOR_EXE):
        if os.path.exists("s2_preprocessor"):
             cmd[0] = "./s2_preprocessor"
        else:
            print("Executable not found. Falling back to 'ingest_planet.py' logic?")
            # We assume user compiled it here.
    
    # Silence output
    try:
        subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except subprocess.CalledProcessError as e:
        print(f"Error running preprocessor for {variant_name}: {e}")
        return False
    return True

def crop_border(variant_name, face_idx, edge_idx):
    # Load the resulting strip file
    # Edge 0 (N), 2 (S) -> Horizontal Strips
    # Edge 1 (E), 3 (W) -> Vertical Strips
    
    # Output files: 
    # {output_prefix}_horizontal_strips.tif
    # {output_prefix}_vertical_strips.tif
    
    path_h = f"{OUTPUT_DIR}/{variant_name}_horizontal_strips.tif"
    path_v = f"{OUTPUT_DIR}/{variant_name}_vertical_strips.tif"
    
    if edge_idx == 0: # North - Top of Horizontal
        # Row: 2 * face_idx
        if not os.path.exists(path_h): return None
        img = Image.open(path_h)
        # Crop: (0, row*P, W+2P, (row+1)*P)
        row = 2 * face_idx
        y = row * PADDING
        return img.crop((0, y, img.width, y + PADDING))
        
    elif edge_idx == 2: # South - Bottom of Horizontal
        # Row: 2 * face_idx + 1
        if not os.path.exists(path_h): return None
        img = Image.open(path_h)
        row = 2 * face_idx + 1
        y = row * PADDING
        return img.crop((0, y, img.width, y + PADDING))
        
    elif edge_idx == 3: # West - Left of Vertical
        # Col: 2 * face_idx
        if not os.path.exists(path_v): return None
        img = Image.open(path_v)
        col = 2 * face_idx
        x = col * PADDING
        return img.crop((x, 0, x + PADDING, img.height))
        
    elif edge_idx == 1: # East - Right of Vertical
        # Col: 2 * face_idx + 1
        if not os.path.exists(path_v): return None
        img = Image.open(path_v)
        col = 2 * face_idx + 1
        x = col * PADDING
        return img.crop((x, 0, x + PADDING, img.height))

def main():
    # TARGETS
    targets = [
        (1, 2), # Face 1 South (Edge 2)
        (1, 1)  # Face 1 East (Edge 1)
    ]
    
    original_topo = load_topology()
    
    for face, edge in targets:
        print(f"Generating variants for Face {face} Edge {edge}...")
        
        # Determine base rotation set
        # Load current
        current = original_topo[face][edge]
        base_rot = current["rot"]
        
        # Valid set is {base, base+180} normalized or {base-90, base+90}?
        # Actually:
        # If Rot is 0 or 180 (Parallel), keep it 0/180.
        # If Rot is 90 or 270 (Perpendicular), keep it 90/270.
        
        rot_pair = []
        if base_rot in [0, 180]:
            rot_pair = [0, 180]
        else:
            rot_pair = [90, 270]
            
        variants = [] # (Name, Image)
        
        for r in rot_pair:
            for f_bool in [False, True]:
                # Apply Config
                topo = load_topology() # Reload fresh or modify copy
                topo[face][edge]["rot"] = r
                topo[face][edge]["flip"] = f_bool
                save_topology(topo)
                
                name = f"F{face}_E{edge}_R{r}_F{f_bool}"
                print(f"  Running {name}...")
                if run_preprocessor(name):
                    img = crop_border(name, face, edge)
                    if img:
                        variants.append((f"Rot {r}, Flip {f_bool}", img))
        
        # Stitch
        # If horizontal (N/S), stack vertically.
        # If vertical (E/W), stack horizontally? Or grid.
        # Let's output a 2x2 Grid.
        if len(variants) == 4:
            # Layout
            # [ R1 F0 ] [ R1 F1 ]
            # [ R2 F0 ] [ R2 F1 ]
            
            w, h = variants[0][1].size
            # Canvas: 2w + padding, 2h + text space
            # Add text height
            txt_h = 30
            grid_img = Image.new('RGB', (w*2 + 20, h*2 + 20 + txt_h*2), (50,50,50))
            draw = ImageDraw.Draw(grid_img)
            
            # 0: R1 F0
            grid_img.paste(variants[0][1], (0, txt_h))
            draw.text((5, 0), variants[0][0], fill="white")
            
            # 1: R1 F1
            grid_img.paste(variants[1][1], (w + 20, txt_h))
            draw.text((w + 25, 0), variants[1][0], fill="white")
            
            # 2: R2 F0
            grid_img.paste(variants[2][1], (0, h + 20 + txt_h*2))
            draw.text((5, h + 20 + txt_h), variants[2][0], fill="white")
            
            # 3: R2 F1
            grid_img.paste(variants[3][1], (w + 20, h + 20 + txt_h*2))
            draw.text((w + 25, h + 20 + txt_h), variants[3][0], fill="white")
            
            out_name = f"debug_F{face}_E{edge}.png"
            grid_img.save(f"../../brain/4929aa7f-3e06-4fb7-baa2-efe831a8eaa7/{out_name}")
            print(f"Saved candidate grid to {out_name}")

    # Restore Original
    save_topology(original_topo)

if __name__ == "__main__":
    main()
